language: node_js
node_js:
  - "5"
  - "6"
  - "node"
env:
  global:
    - ENCRYPTION_LABEL="abd15e3073ee"
    - GIT_NAME="Mohamed Kholy"
    - GIT_EMAIL="mkh117@gmail.com"
before_install:
  # Install yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
install:
  - yarn
before_script:
  - export CHROME_BIN=chromium-browser
  # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Workaround for https://github.com/angular/angular-cli/issues/2799
  # see https://github.com/angular/angular-cli/pull/2881
  - cp patches/ngtools-webpack-1.1.4/loader.js node_modules/@ngtools/webpack/src/loader.js
script:
  - cp .env.travis .env
  # - yarn run stat
  # - yarn test -- --ci
  - yarn run build
after_script:
  - yarn add coveralls
  - yarn run coveralls
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch: master
cache:
  directories:
  - $HOME/.yarn-cache
sudo: required
